# Generated by Django 3.2.9 on 2022-02-06 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertiseapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ad',
            name='description1',
            field=models.TextField(default='Check our page!'),
        ),
        migrations.AddField(
            model_name='ad',
            name='description2',
            field=models.TextField(default='Check our page!'),
        ),
        migrations.AddField(
            model_name='ad',
            name='picture',
            field=models.ImageField(blank=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='ad',
            name='username',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
