# Generated by Django 3.2.9 on 2022-02-14 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertiseapp', '0002_auto_20220206_1212'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ad',
            name='picture',
            field=models.ImageField(upload_to='pics'),
        ),
    ]
