# Generated by Django 3.2.9 on 2022-02-16 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertiseapp', '0003_alter_ad_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ad',
            name='posttype',
            field=models.CharField(choices=[('N', 'normal'), ('B', 'bronze'), ('S', 'silver'), ('G', 'gold')], max_length=15),
        ),
    ]
